name: Build

on:
  push:
    branches:
      - master

env:
  DEPLOYMENT_REPOSITORY_ID: gs-nexus
  DEPLOYMENT_REPOSITORY: gs-nexus::default::https://repo.glencoesoftware.com/repository/jzarr-snapshots/
  NEXUS_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Blosc native library
        run: sudo apt-get install -y libblosc1

      - name: Set up latest Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Maven deployment environment
        run: |
          touch maven.properties
          mkdir -p ${HOME}/.m2/
          envsubst < settings.xml > ${HOME}/.m2/settings.xml

      - name: Run tests
        run: mvn -B test

      - name: Deploy
        run: mvn -B -DaltDeploymentRepository=${DEPLOYMENT_REPOSITORY} deploy

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/*.jar
